#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class InterestingParty {
public:
  int bestInvitation(vector <string> first, vector <string> second) {
    map<string, int> m;
    int i = 0; 
    int size = first.size();
    for (; i < size; ++i) {
      ++m[first[i]];
      ++m[second[i]];
    }

    int maxValue = 0;
    for (auto i : m) {
      if (i.second > maxValue)
        maxValue = i.second;
    }
    return maxValue;
  }
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, vector <string> p1, bool hasAnswer, int p2) {
  cout << "Test " << testNum << ": [" << "{";
  for (int i = 0; int(p0.size()) > i; ++i) {
    if (i > 0) {
      cout << ",";
    }
    cout << "\"" << p0[i] << "\"";
  }
  cout << "}" << "," << "{";
  for (int i = 0; int(p1.size()) > i; ++i) {
    if (i > 0) {
      cout << ",";
    }
    cout << "\"" << p1[i] << "\"";
  }
  cout << "}";
  cout << "]" << endl;
  InterestingParty *obj;
  int answer;
  obj = new InterestingParty();
  clock_t startTime = clock();
  answer = obj->bestInvitation(p0, p1);
  clock_t endTime = clock();
  delete obj;
  bool res;
  res = true;
  cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
  if (hasAnswer) {
    cout << "Desired answer:" << endl;
    cout << "\t" << p2 << endl;
  }
  cout << "Your answer:" << endl;
  cout << "\t" << answer << endl;
  if (hasAnswer) {
    res = answer == p2;
  }
  if (!res) {
    cout << "DOESN'T MATCH!!!!" << endl;
  } else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
    cout << "FAIL the timeout" << endl;
    res = false;
  } else if (hasAnswer) {
    cout << "Match :-)" << endl;
  } else {
    cout << "OK, but is it right?" << endl;
  }
  cout << "" << endl;
  return res;
}
int main() {
  bool all_right;
  all_right = true;
	
  vector <string> p0;
  vector <string> p1;
  int p2;
	
  {
    // ----- test 0 -----
    string t0[] = {"fishing","gardening","swimming","fishing"};
    p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
    string t1[] = {"hunting","fishing","fishing","biting"};
    p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
    p2 = 4;
    all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
    // ------------------
  }
	
  {
    // ----- test 1 -----
    string t0[] = {"variety","diversity","loquacity","courtesy"};
    p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
    string t1[] = {"talking","speaking","discussion","meeting"};
    p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
    p2 = 1;
    all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
    // ------------------
  }
	
  {
    // ----- test 2 -----
    string t0[] = {"snakes","programming","cobra","monty"};
    p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
    string t1[] = {"python","python","anaconda","python"};
    p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
    p2 = 3;
    all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
    // ------------------
  }
	
  {
    // ----- test 3 -----
    string t0[] = {"t","o","p","c","o","d","e","r","s","i","n","g","l","e","r","o","u","n","d","m","a","t","c","h","f","o","u","r","n","i"};
    p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
    string t1[] = {"n","e","f","o","u","r","j","a","n","u","a","r","y","t","w","e","n","t","y","t","w","o","s","a","t","u","r","d","a","y"};
    p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
    p2 = 6;
    all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
    // ------------------
  }
	
  if (all_right) {
    cout << "You're a stud (at least on the example cases)!" << endl;
  } else {
    cout << "Some of the test cases had errors." << endl;
  }
  return 0;
}
// PROBLEM STATEMENT
// Mr. White is a very versatile person - absolutely everything is interesting to him. Perhaps this is why he has many friends. Quite unfortunately, however, none of his friends are versatile at all. Each of them is interested only in two topics and refuses to talk about anything else. Therefore, each time Mr. White organizes a party, it's a big problem for him to decide whom to invite so that the party is interesting to everybody. 
// Now that Mr. White has a lot of experience in organizing parties, he knows for sure that a party will be interesting if and only if there's a topic interesting to each of the invited friends.
// 
// You will be given vector <string>s first and second. The i-th friend of Mr. White is interested in topics first[i] and second[i]. 
// Return the largest number of friends that Mr. White can invite to his party so that the party will be interesting.
// 
// DEFINITION
// Class:InterestingParty
// Method:bestInvitation
// Parameters:vector <string>, vector <string>
// Returns:int
// Method signature:int bestInvitation(vector <string> first, vector <string> second)
// 
// 
// CONSTRAINTS
// -first will contain between 1 and 50 elements, inclusive.
// -second will contain the same number of elements as first.
// -Each element of first and second will contain between 1 and 15 characters, inclusive.
// -Each character in first and second will be a lowercase letter ('a'-'z').
// -For each valid i, first[i] will not be the same as second[i].
// 
// 
// EXAMPLES
// 
// 0)
// {"fishing", "gardening", "swimming", "fishing"}
// {"hunting", "fishing", "fishing", "biting"}
// 
// Returns: 4
// 
// This is a very easy case since everybody is interested in "fishing".
// 
// 1)
// {"variety", "diversity", "loquacity", "courtesy"}
// {"talking", "speaking", "discussion", "meeting"}
// 
// Returns: 1
// 
// Despite being interested in "talking", "speaking", "meeting" and so on, these people have nothing to talk about with each other.
// 
// 2)
// {"snakes", "programming", "cobra", "monty"}
// {"python", "python", "anaconda", "python"}
// 
// Returns: 3
// 
// Mr. White can invite friends 0, 1, 3 (0-based) and they will have an interesting evening talking about "python" (or at least Mr. White thinks so).
// 
// 3)
// {"t", "o", "p", "c", "o", "d", "e", "r", "s", "i", "n", "g", "l", "e", "r",
//  "o", "u", "n", "d", "m", "a", "t", "c", "h", "f", "o", "u", "r", "n", "i"}
// {"n", "e", "f", "o", "u", "r", "j", "a", "n", "u", "a", "r", "y", "t", "w", 
//  "e", "n", "t", "y", "t", "w", "o", "s", "a", "t", "u", "r", "d", "a", "y"}
// 
// Returns: 6
// 
// 
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!

