#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class TextStatistics {
private:
	bool isWordChar(char c) {
		return ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z');
	}

public:
	double averageLength(string text) {
		int numWords = 0, numChars = 0;
		enum State { INWORD, OUTWORD };
		State s = OUTWORD;
		for (auto c : text) {
			switch(s) {
			case OUTWORD:
				if (isWordChar(c)) {
					s = INWORD;
					numWords++;
					numChars++;
				}
				break;
			case INWORD:
				if (isWordChar(c))
					numChars++;
				else
					s = OUTWORD;
				break;
			}
		}
		return (numWords == 0) ? 0 : (numChars / (double)numWords);
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, string p0, bool hasAnswer, double p1) {
	cout << "Test " << testNum << ": [" << "\"" << p0 << "\"";
	cout << "]" << endl;
	TextStatistics *obj;
	double answer;
	obj = new TextStatistics();
	clock_t startTime = clock();
	answer = obj->averageLength(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == answer && fabs(p1 - answer) <= 1e-9 * max(1.0, fabs(p1));
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	string p0;
	double p1;
	
	{
	// ----- test 0 -----
	p0 = "This is div2 easy problem.";
	p1 = 4.0;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	p0 = "Hello, world!";
	p1 = 5.0;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	p0 = "Simple";
	p1 = 6.0;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	p0 = "";
	p1 = 0.0;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	p0 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	p1 = 50.0;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// 
// Most modern text editors are able to give some statistics about the text they are editing.  One nice statistic is the average word length in the text.
// 
// 
// A word is a maximal continuous sequence of letters ('a'-'z', 'A'-'Z').  Words can be separated by spaces, digits, and punctuation marks.
// 
// 
// The average word length is the sum of all the words' lengths divided by the total number of words.  For example, in the text "This is div2 easy problem.", there are 5 words: "This", "is", "div", "easy", and "problem".  The sum of the word lengths is 4+2+3+4+7=20, so the average word length is 20/5=4.
// 
// 
// Given a string text, return the average word length in it.  If there are no words in the text, return 0.0.
// 
// 
// 
// DEFINITION
// Class:TextStatistics
// Method:averageLength
// Parameters:string
// Returns:double
// Method signature:double averageLength(string text)
// 
// 
// NOTES
// -The returned value must be accurate to within a relative or absolute value of 1E-9.
// 
// 
// CONSTRAINTS
// -text will contain between 0 and 50 characters, inclusive.
// -text will contain only letters ('a'-'z', 'A'-'Z'), digits ('0'-'9'), spaces, and the following punctuation marks: ',', '.', '?', '!', '-'.
// 
// 
// EXAMPLES
// 
// 0)
// "This is div2 easy problem."
// 
// Returns: 4.0
// 
// The example from the problem statement.
// 
// 1)
// "Hello, world!"
// 
// Returns: 5.0
// 
// In this case all words have the same length.
// 
// 2)
// "Simple"
// 
// Returns: 6.0
// 
// One word.
// 
// 3)
// ""
// 
// Returns: 0.0
// 
// No words here, so return 0.
// 
// 4)
// "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
// 
// Returns: 50.0
// 
// 
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
